### ISSUE TITLE
¿Cuántas peticiones puede satisfacer simultáneamente un consumer?

### ISSUE THREAD

**Issue by Juanma-Sanchez** [guiloga/guirpc#2]
Hola @guiloga, tenía una consulta sobre el funcionamiento de guirpc (si no es problema responderla). ¿Puede un único consumer atender a varias solicitudes simultáneamente o sería necesario ejecutar varios para este propósito?

**Comment by guiloga** [comment]
Hola Juanma,

Me alegra que me preguntes esto. La versión inicial 0.1 (la única por ahora) solo permite manejar 1 petición simúltanemante por consumidor, en otras palabras, un consumer o worker es single-threaded y solo puede procesar 1 evento/mensaje de la cola.
Para escalar y aumentar así el rendimiento tendrías que levantar varias réplicas del mismo consumidor/worker.

No obstante, la idea para una versión siguiente (además de otras mejoras) es hacer el consumidor multi-threaded fijando un número de workers/hilos máximo en la config para ese consumidor. De este modo podrías escalar horizontalmente aumentando el número de replicas del consumidor o verticalmente aumentando el número de hilos de un determinado consumidor.

Si te digo la verdad, hice el paquete con una idea básica de inicio con intención de llevar a cabo varias mejoras que tenía pensadas posteriormente para el paquete que no he llevado a cado aún y 1 de ellas era ésta.

En caso de que quieras colaborar para extenderlo y/o construir un nuevo paquete a partir de este más serio (que es algo que también tengo pensado) lo podemos hablar.
Te envío también la referencia de otro paquete que encontré parecido pero más profesional y en este caso usando redis queues y **asyncio** para la concurrencia.

Un saludo!

**Comment by guiloga** [comment]
Ahora lo he adjuntado, este es [Arq](https://github.com/samuelcolvin/arq)

**Comment by Juanma-Sanchez** [comment]
Muchas gracias Guillem.

**Comment by guiloga** [comment]
Hola Juanma,

la rama master contiene los cambios nuevos para el multi-threading por si quieres probarlo.
Hay que establecer el parámetro workers=$int en la sección [server.options] de la config del consumidor.
El número de workers o hilos es el máximo de mensajes consurrentes que puede manejar el servidor o consumer.

Lo he probado con un script que lanza n peticiones simulatáneamente y funciona bien aunque faltaría hacer los tests.

Un saludo.

**Comment by Juanma-Sanchez** [comment]
Hola Guillem,

Ya he probado los cambios y funciona perfectamente.

De hecho ha sido más problemático lanzar n peticiones que responderlas. He tenido que hacerlo multiproceso porque algunas fallaban con hilos de ejecución. ¿Sabes si puede ser porque tenga algo mal configurado?

Muchas gracias y un saludo.

**Comment by guiloga** [comment]
Hola Juanma,

Genial! 
Pues a mi también me costó lanzar las peticiones simultáneas y multi-hilo me fallaba alguna petición random, nose si puede ser un bug relacionado con el cliente, el productor que es la clase **amqp.utils.ClientConnector**.
No estoy seguro, pero ahora que lo dices también me pasó y lo obvie en ese momento.

Estos son los cambios que quiero meter en la versión 2:
[Tasks](https://github.com/guiloga/guirpc/blob/master/notes.txt)
Falta la de SSL y la doc.

También 2 fixes que ya están en la rama master.
Uno de ellos también relacionado con la clase ClientConnector, al realizar varias peticiones desde el mismo cliente se cerraba la conexión, expiraba al cabo de un tiempo por timeout y no era capaz de auto reconectar con el servidor de RabbitMQ. 

Saludos.
Guillem
